density:
  basis: linear
  gradient scale length: 333.33333um
  max: 0.3
  min: 0.2
  noise:
    max: 1.0e-09
    min: 1.0e-10
    type: uniform
drivers:
  E0:
    delta_omega_max: 0.015
    envelope:
      tc: 200.25ps
      tr: 0.1ps
      tw: 400ps
      xc: 50um
      xr: 0.2um
      xw: 1000um
      yc: 50um
      yr: 0.2um
      yw: 1000um
    num_colors: 64
    shape: arbitrary
    params:
      amplitudes: 
        init: random # uniform, random
        learned: true
        activation: log # linear, log
      phases:
        init: random # random, seed-###
        learned: true 
        seed: 42

grid:
  boundary_abs_coeff: 1.0e4
  boundary_width: 3um
  dt: 0.001ps
  dx: 30nm
  low_pass_filter: 0.66
  tmax: 15.0ps
  tmin: 0.0ns
  ymax: 3um
  ymin: -3um


parsl:
  provider: local
  nodes: 128
  walltime: 01:00:00

mlflow:
  experiment: opt-64lines-504points
  run: temperature=2000.0-gsl=333.3-intensity=7.00e+14
save:
  fields:
    t:
      dt: 1ps
      tmax: 10ps
      tmin: 0ps
    x:
      dx: 80nm
    y:
      dy: 128nm
solver: envelope-2d
terms:
  epw:
    boundary:
      x: absorbing
      y: periodic
    damping:
      collisions: 1.0
      landau: true
    density_gradient: true
    linear: true
    source:
      noise: true
      tpd: true
  zero_mask: true
units:
  atomic number: 40
  envelope density: 0.25
  ionization state: 6
  laser intensity: 7.0e14 W/cm^2
  laser_wavelength: 351nm
  reference electron temperature: 2000 eV
  reference ion temperature: 1000eV
opt:
  learning_rate: 0.01
  batch_size: 1
  decay_steps: 100000
  method: scipy
  metric_time_in_ps: 6.0